name: Require Labels

on:
  pull_request:

jobs:
  check:
    name: Verify Labels

    runs-on: ubuntu-latest

    steps:
    - uses: gmurphey/require-labels@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
