name: Require Labels

on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  check:
    name: Verify Labels

    runs-on: ubuntu-latest

    steps:
    - uses: gmurphey/require-labels@documentation
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
